
char *wait_ascii[]={
  "                                                               ",
  "                                                               ",
  "                                                               ",
  "                                                               ",
  "                                                               ",
  "                 xxxxxxxxxxx                                   ",
  "                 xx       xx                                   ",
  "                  xx     xx                                    ",
  "                   x     x                                     ",
  "     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                      ",
  "     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                      ",
  "    xxxxxxxxxxxxxxxxxx xxxxxxxxxxxxxxxxxxx                     ",
  "    xxxxxxxxxxxxxxxxx  xxxxxxxxxxxxxxxxxxx                     ",
  "   xxxxxxxxxxxxxxxxxxx xxxxxxxxxxxxxxxxxxxx                    ",
  "   xxxxxxxxxxxxxxxx       xxxxxxxxxxxxxxxxx                    ",
  "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                   ",
  "  xxxxxxxxx      xx       xx  xxxx  xxxxxxxx                   ",
  " xxxxxxxxxxxx  xxxx  xxx  xx    xx  xxxxxxxxx                  ",
  " xxxxxxxxxxxx  xxxx  xxx  xx  x  x  xxxxxxxxx                  ",
  "xxxxxxxxxxxxx  xxxx       xx  xx    xxxxxxxxxx                 ",
  "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                 ",
};

#include <stdio.h>

int main(int argc,char **argv)
{
  #define SPRITE_LEN 8*21
  unsigned char sprite[SPRITE_LEN];

  for(int i=0;i<SPRITE_LEN;i++) sprite[i]=0;

  printf("// Auto-generated by tools/sprite_gen.c.\n");
  printf("#include \"includes.h\"\n");
  printf("uint8_t wait_sprite[%d]={\n",SPRITE_LEN);
  for(int row=0;row<21;row++) {
    for(int col=0;col<64;col++) {
      if (wait_ascii[row][col]!=' ') {
	sprite[row*8+(col>>3)]|=1<<(col&7);
      }
    }

    for(int byte=0;byte<8;byte++) {
      printf("0x%02x",sprite[row*8+byte]);
      if (byte<7||row<20) printf(", "); else printf("  ");
    }
    printf("// \"%s\"\n", wait_ascii[row]);
  }
  printf("};\n");

  
}
